
name: Deploy Necesse

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:  
 bicepAzCliDeploy:
    name: Bicep Az CLI Deploy jobs
    runs-on: ubuntu-latest
  
    env:
      resource_group_name: rg-necesse
      location: eastus2
      aci_name: aci-necesse
      vnet_name: vn-necesse
      aci_subnet_name: sn-aci-necesse
      public_ip_address_name: ip-necesse
      image_name: pixil/necesse
      app_gateway_name: ag-necesse
      load_balancer_name: lb-necesse
    
    steps:      
      - uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy Resource Group'
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment sub create \
            --name ${{ env.resource_group_name }} \
            --location "${{ env.location }}" \
            --template-file ./bicep-files/resourcegroup.bicep \
            --parameters \
            resourceGroupName=${{ env.resource_group_name}} \
            location="${{ env.location }}"

      - name: 'Deploy Storage'
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment group create \
            --resource-group ${{ env.resource_group_name }} \
            --template-file ./bicep-files/storage.bicep \
            --parameters \
            location="${{ env.location }}" 
      
      - name: 'Deploy Virtual Network'
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment group create \
            --resource-group ${{ env.resource_group_name }} \
            --template-file ./bicep-files/vnet.bicep \
            --parameters \
            location="${{ env.location }}" 
            vnetName="${{ env.vnet_name }}" 
            aciSubnetName="${{ env.aci_subnet_name }}" 
            publicIpAddressName="${{ env.public_ip_address_name }}" 

      - name: 'Deploy ACI'
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment group create \
            --resource-group ${{ env.resource_group_name }} \
            --template-file ./bicep-files/aci.bicep \
            --parameters \
            name="${{ env.aci_name }}" \
            location="${{ env.location }}" \
            vnetName="${{ env.vnet_name }}" \
            image="${{ env.image_name }}" 

      - name: 'Deploy Load Balancer'
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment group create \
            --resource-group ${{ env.resource_group_name }} \
            --template-file ./bicep-files/loadbalancer.bicep \
            --parameters \
            lbName="${{ env.load_balancer_name }}" \
            location="${{ env.location }}" \
            publicIpName="${{ env.public_ip_address_name }}" \
            vnetName="${{ env.vnet_name }}" \
     