
name: Deploy Necesse

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:  
 bicepAzCliDeploy:
    name: Bicep Az CLI Deploy jobs
    runs-on: ubuntu-latest
  
    env:
      resource_group_name: rg-necesse
      location: East US
    
    steps:      
      - uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}